[WnB] 예약API DELETE 구현
wecode-bootcamp-korea/35-2nd-WnB-backend pull request #10
Opened 2022-08-05 08:55 UTC by kdylsky

## :: 최근 작업 주제 
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
- 예약된 숙박에 대한 취소 API구현

<br />

## :: 구현 사항 설명 
사용자로 부터 입력 받는 예약번호를 이용해서 방예약을 취소하게 구현했다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
없습니다.

<br />

## :: 기타 질문 및 특이 사항
없습니다.

2022-08-05 09:02 UTC, bigfanoftim requested changes

2022-08-05 09:02 UTC, bigfanoftim commented on reservations/views.py
> +            user                    = request.user
```suggestion
```
재활용되지 않는 변수라 굳이 저장해서 사용할 필요가 없을 것 같아요!! 무엇보다 `request.user` 정도면 가독성에 문제도 없을 것 같구요.

2022-08-09 11:54 UTC, kdylsky commented
코드리뷰 반영 후 변경 사항

1. pathParameter를 작성하여 두가지 경우로 나누었습니다.
(1) 127.0.0.1/reservations 으로 들어 왔을 경우는 ReservationView의 get과 post
(2)127.0.0.1/reservations/<str:reservation_numbe>로 들어왔을 경우는 ReservationView의 Delete


2.

2022-08-11 02:15 UTC, kdylsky commented
다른 PR을 올려 close 하겠습니다.

2022-08-11 02:15 UTC, closed without merging