[WnB] 유효성 검사
wecode-bootcamp-korea/35-2nd-WnB-backend pull request #12
Opened 2022-08-08 08:12 UTC by ooooo5h

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 새 브랜치 생성 및 유효성 검사 코드 분리

<br />

## :: 구현 사항 설명
1. first_name : 한글만
2. last_name : 한글만
3. phone_number : '010-111-1111'

<br />

## :: 성장 포인트
- 없음

<br />

## :: 기타 질문 및 특이 사항
- 없음

2022-08-08 08:54 UTC, ooooo5h commented on core/utils.py
> +    return wrapper
아직 merge전인 코드가 올라와있는 이유 생각해보기
그리고 해당 브랜치가 merge됐을 경우 어떻게 될지 생각해보기

2022-08-08 09:19 UTC, bigfanoftim requested changes

2022-08-08 09:19 UTC, bigfanoftim commented on core/utils.py
> +    return wrapper
정말 머지되지 않은 다른 브랜치의 코드가 올라와있는거보니~~ 문제가 잇군요 ㅎㅎ 수정해서 다시 올려주세요~

2022-08-09 04:00 UTC, bigfanoftim approved these changes
LGTM 👍

2022-08-09 04:00 UTC, merged