[WnB] 호스트 집 등록 API(미완성)
wecode-bootcamp-korea/35-2nd-WnB-backend pull request #16
Opened 2022-08-09 16:21 UTC by ooooo5h

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- S3이미지 등록 빼고 집 등록 완료
- AWS S3 사용하여 집 등록 기능 구현하기

<br />

## :: 구현 사항 설명(미완성)
1. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 아직 완성전이라 주석이 남아있습니다. AWS S3까지 추가 후 주석 삭제해서 다시 올리겠습니다!!

2022-08-10 08:51 UTC, bigfanoftim requested changes

2022-08-10 08:51 UTC, bigfanoftim commented on hosts/views.py
> +            }
HTTP POST Method인데 왜 get의 역할을 함께 하고 있을까요?
만약 업로드가 성공되고 다시 그 페이지 로딩에 필요한 데이터를 주기 위함이라면 그럴 필요가 없습니다.
그건 해당 상세 페이지에 필요한 데이터를 전달하는 다른 api가 있어야겠죠!

2022-08-10 10:42 UTC, ooooo5h commented on hosts/views.py
> +            }
넵 이해했습니다!! 감사합니다 호준님
프론트와 이야기해서 필요한 데이터만 보내주는 걸로 data 수정했습니다! 
아직 반환하는 데이터를 어떤 걸 줘야하고, 어쩔 때 줘야하는지 감을 못잡겠네요... 흑

2022-08-10 10:47 UTC, ooooo5h commented on hosts/views.py
> +            return JsonResponse({'message':'SUCCESS', 'room':data}, status=201)
이미지 사진이 없는 룸의 경우에는 "room_images" : [] 처럼 빈 리스트로 반환됩니다.
값이 없을때 해당 줄은 아예 안보이게 처리하고 싶은데 어떻게 하면 좋을까요
(나혼자 일단 짜보고 질문하기)

2022-08-11 07:52 UTC, bigfanoftim approved these changes
LGTM 👍  Conflict만 해결해 주세요!

2022-08-11 08:11 UTC, merged