[wnb] 예약 상세페이지 구현
wecode-bootcamp-korea/35-2nd-WnB-backend pull request #19
Opened 2022-08-10 10:49 UTC by kdylsky

## :: 최근 작업 주제
- [x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
- 예약 상세페이지 출력 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인 예약 화면에서 개별 예약 상세페이지로 이동 후 예약 내용 출력
- path parameter로 예약 번호를 이용해서 특정 예약정보를 출력하게 구현했습니다.

<br />

## :: 성장 포인트 
path parameter를 사용해서 특정 예약된 정보에 접근하는 방법을 알게되었습니다.
path parameter를 이용해 RESTful한  엔드포인트 설계에 대해서 생각해볼 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 없습니다.

2022-08-10 12:12 UTC, bigfanoftim requested changes

2022-08-10 12:12 UTC, bigfanoftim commented on reservations/views.py
> +                                                  .filter(user = request.user).get(number = reservation_number)
```suggestion
                                                  .get(user = request.user, number = reservation_number)
```
굳이 filter에 get을 섞어 쓸 필요가 없어보여요!

2022-08-10 12:23 UTC, kdylsky commented on reservations/views.py
> +                                                  .filter(user = request.user).get(number = reservation_number)
수정 후 pr요청 드리겠습니다.

2022-08-11 01:52 UTC, bigfanoftim approved these changes
LGTM 👍

2022-08-11 01:52 UTC, merged