[WnB] 모델링 완료
wecode-bootcamp-korea/35-2nd-WnB-backend pull request #3
Opened 2022-08-02 09:18 UTC by kdylsky

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
- 모델링 구현입니다.

<br />

## :: 구현 사항 설명 
1. 앱 생성 후 모델링 작성

<br />

## :: 성장 포인트 
없습니다.

<br />

## :: 기타 질문 및 특이 사항
없습니다.

2022-08-02 10:22 UTC, bigfanoftim requested changes

2022-08-02 10:22 UTC, bigfanoftim commented on rooms/models.py
> +    longitude            = models.CharField(max_length = 50)
decimal로 저장하면 어떨까요?

2022-08-02 10:22 UTC, bigfanoftim commented on rooms/models.py
> +        db_table    = 'rooms_room_facilities'
```suggestion
    room_type            = models.ForeignKey('RoomType', on_delete = models.CASCADE)
    facilities = models.ManyToManyField('Facility', through='RoomFacility')

class Facility(models.Model):
    name                 = models.CharField(max_length = 50)

    class Meta:
        db_table    = 'facilities' 

class RoomFacility(models.Model):
    room            = models.ForeignKey('Room', on_delete = models.CASCADE)
    room_facility   = models.ForeignKey('RoomFacility', on_delete = models.CASCADE)

    class Meta:
        db_table    = 'rooms_facilities'
```

ManyToMany는 이런식으로 작성해야 할 것 같습니다.

2022-08-02 10:22 UTC, bigfanoftim commented on rooms/models.py
> +        db_table    = 'rooms_room_facilities'
room에서 facilities를 접근해야하는 것이기 때문에 room쪽에 필드를 추가했습니다.
```python
room = Room.objects.get(id=1)
room.facilities ...
```

2022-08-02 10:53 UTC, kdylsky commented on rooms/models.py
> +    longitude            = models.CharField(max_length = 50)
멘토님 varchar말고 decimal을 사용하는 이유가 있을 까요?

2022-08-02 11:23 UTC, kdylsky commented
rebase까지 작업 후 push하는 과정에서 ''https://github.com/wecode-bootcamp-korea/35-2nd-WnB-backend.git'에 푸시하는데 실패했습니다. 힌트: 현재 브랜치의 끝이 리모트 브랜치보다 뒤에 있으므로 업데이트가 거부되었습니다.'..잠시만요

2022-08-02 11:44 UTC, bigfanoftim requested changes

2022-08-02 11:44 UTC, bigfanoftim commented on rooms/models.py
> +    facility             = models.ManyToManyField('Facility', through = 'RoomFacility')
ManyToManyField는 복수형으로 작성해주세요.

2022-08-02 11:44 UTC, bigfanoftim commented on rooms/models.py
> +    longitude            = models.CharField(max_length = 50)
소수점으로 다뤄지는 값이니 당연히 decimal로 해야한다고 봐야겠죠?
굳이 아무런 이유없이 string으로 저장하게 되면 훗날 거리를 계산하는 api를 작성하게 되면 문제가 됩니다.

2022-08-02 11:50 UTC, bigfanoftim commented
> rebase까지 작업 후 push하는 과정에서 ''[https://github.com/wecode-bootcamp-korea/35-2nd-WnB-backend.git'에](https://github.com/wecode-bootcamp-korea/35-2nd-WnB-backend.git'%EC%97%90) 푸시하는데 실패했습니다. 힌트: 현재 브랜치의 끝이 리모트 브랜치보다 뒤에 있으므로 업데이트가 거부되었습니다."라는 에러를 만났습니다. 그래서 'git push origin --force'명령어를 써서 해결했는데 혹시 다른 방법이 있었을까요? 아직 force를 써야하는 경우와 그러지 않은 경우가 구분이 안됩니다.

rebase 이후 커밋이 달라져 그렇습니다. force 푸시를 하지 않고 해결하려면 remote 브랜치를 지우고 다시 push 하는 방법이 있겠습니다. 제 생각에는 먼저 해당 에러메세지가 왜 발생하는지 정확히 이해하실 필요가 있어보입니다.

2022-08-02 11:57 UTC, kdylsky commented
저희가 처음에 class Room을 정의할 때 class Meta를 정의하지 않고 migration까지 진행했더라구요 그래서 db 테이블의 이름이 'rooms_room'으로 생성이 됐습니다. 그래서 다시 class Meta를 추가했고 migrate, migration을 진행했으니 해당 class에 변경사항이 db에 적용이 되겠거니 했습니다. 하지만 db에는 계속 rooms_room이 남아있었고, rooms 테이블이 생성되지 않았습니다. 그래서 sql명령문으로 rooms_room 이름을 수동으로 rooms으로 변경했는데 변경되지 않은 이유가 있을까요..? 그리고 이름을 바꾸는 방법말고 다른 해결 방법이 있을까요? - 계속 추가되는 코멘트에 죄송합니도...-

2022-08-02 11:59 UTC, kdylsky commented on rooms/models.py
> +    longitude            = models.CharField(max_length = 50)
만약에 string으로 저장했다면, 계산식을 작성할때 형변환을 사용했다면 그것도 가능한 방법일까요? 위도, 경도처럼 소수점으로 다뤄지는 값들은 decimal을 사용하도록 하겠습니다!

2022-08-02 12:06 UTC, kdylsky commented on rooms/models.py
> +    facility             = models.ManyToManyField('Facility', through = 'RoomFacility')
컨벤션 때문에 복수로 작성을 해야 하는 건가요?

2022-08-02 15:51 UTC, ooooo5h commented on rooms/models.py
> +        db_table    = 'rooms_room_facilities'
다대다의 경우 어느쪽에 해당 필드를 추가해야하는지 어려웠는데 
들어주신 예시처럼 생각해보면 조금 더 쉽게 모델링 할 수 있을 것 같네요..! 반영했습니다!

2022-08-02 23:02 UTC, ooooo5h commented on rooms/models.py
> +    room_facility        = models.ForeignKey('Facility', on_delete = models.CASCADE)
이름 수정1

2022-08-02 23:02 UTC, ooooo5h commented on users/models.py
> +    point               = models.DecimalField(max_digits = 10, decimal_places = 2)
기본값 설정

2022-08-03 00:27 UTC, bigfanoftim requested changes

2022-08-03 00:27 UTC, bigfanoftim commented on users/models.py
> +    kakao_id            = models.CharField(max_length = 50)
varchar보다 bigint가 더 효율적일 것 같습니다!

2022-08-03 00:28 UTC, bigfanoftim commented
> 우리가 사용하는 카카오 id가 문자열이기 때문).
이건 무슨 의미일까요?

2022-08-03 00:38 UTC, kdylsky commented on users/models.py
> +    kakao_id            = models.CharField(max_length = 50)
넵!

2022-08-03 00:48 UTC, kdylsky commented
> > 우리가 사용하는 카카오 id가 문자열이기 때문).
> 
> 이건 무슨 의미일까요?

사용자의 카카오톡 id 자체를 저장하려고 했습니다! (ex: bigfanoftim)

2022-08-03 01:08 UTC, bigfanoftim commented
> 사용자의 카카오톡 id 자체를 저장하려고 했습니다! (ex: bigfanoftim)

아하~ 그건 id가 아니라 username 혹은 email 이라는 키워드로 사용됩니다. 여기서 받는 id는 1923618736 이런 값입니다!

2022-08-03 01:08 UTC, bigfanoftim approved these changes
LGTM 👍

2022-08-03 01:08 UTC, merged