예약API  GET 구현
wecode-bootcamp-korea/35-2nd-WnB-backend pull request #7
Opened 2022-08-05 08:12 UTC by kdylsky

## :: 최근 작업 주제 
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 예약 API 중 GET METHOD를 구현했습니다.

<br />

## :: 구현 사항 설명 
- user가 가지는 예약에 대해서 select_related 와 prefetch_related를 이용해서 쿼리셋 데이터를 가지고 와서 저장 후 아래의 코드에서 사용하게 구현했습니다.

- 리스트 컴프리헨션을 이용해서 for문을 돌면서 예약 정보를 하나씩 출력하게 구현했습니다. 

<br />

## :: 성장 포인트
- select_related 와 prefetch_related를 이용해서 데이터베이스에 최대한 접근하는 것을 제한 하는 식으로 구현해보았습니다. 오늘 orm최적화 수업을 듣고, 단순히 구현만이 아닌, 데이터베이스와 서버 사이의 통신에 부담이 되지 않는 것도 고려해야 한다는 점을 알게 되었고, 이번 API를 구현하면서 실습으로 활용해 보았습니다.

<br />

## :: 기타 질문 및 특이 사항
-  현재 다른 분들의 구현이 완료 되지 않아 구현 완료후 내용이 변경될 가능성이 있습니다. 
-  추가로 구현해야 하는 사항이 있을것으로 보이며, 그전에 현재 구현한 로직에 대해서 어떤지 리뷰를 받고자 PR요청을 드립니다.

2022-08-05 08:41 UTC, bigfanoftim requested changes
LGTM 👍 
테스트 코드만 추가로 작성해주시면 좋을 것 같아요~

2022-08-05 08:41 UTC, bigfanoftim commented on reservations/urls.py
> +    path('/reservation', ResevationsView.as_view())
```suggestion
    path('', ResevationsView.as_view())
```
```python
GET :8000/reservations # 예약 리스트
POST :8000/reservations # 예약하기
```

현재 코드로는 `:8000/reservations/reservation` 일 것 같은데 suggestion과 같이 수정해주세요!

2022-08-05 08:41 UTC, bigfanoftim commented on reservations/views.py
> +        user            = User.objects.get(id = request.id)
```suggestion
```

2022-08-05 08:41 UTC, bigfanoftim commented on reservations/views.py
> +    def get(self, request):
```suggestion
    @decorator
    def get(self, request):
```

2022-08-05 08:41 UTC, bigfanoftim commented on reservations/views.py
> +                                             .filter(user_id=user.id)
```suggestion
                                             .filter(user=request.user)
```

2022-08-08 02:45 UTC, bigfanoftim requested changes

2022-08-08 02:45 UTC, bigfanoftim commented on rooms/views.py
> +
이상한게 올라와있네요~ push 하시고 라벨바꾸실 때는 항상 본인 PR에 어떤 코드가 올라왔는지 확인하셔야 합니다.

2022-08-08 02:50 UTC, kdylsky commented on rooms/views.py
> +
죄송합니다
다른 pr도 다시 확인후 요청 드리겠습니다.

2022-08-08 03:39 UTC, kdylsky commented on rooms/views.py
> +
추적을 제외하는 git rm --cached rooms/ -r 을 하고 난 뒤 수정을 한뒤 올렸으나, 추적이 제외되지 않았습니다.

혹시 다른 방법이 있는 건가요?

아니면 원래 rooms이 변경 되었기 때문에 올라가게 되는 건가요?

2022-08-08 07:05 UTC, bigfanoftim requested changes
LGTM 👍  
login decorator 머지되면 그에 맞게 코드 전체적으로 수정해주시고 라벨 변경해주세요~!

2022-08-09 05:01 UTC, kdylsky commented
> LGTM 👍 login decorator 머지되면 그에 맞게 코드 전체적으로 수정해주시고 라벨 변경해주세요~!

decorator merge후 변경사항입니다.

1. reservations.view 파일의 uesr = user.request을 만들어 주었습니다.
- 아래의 filter에서만 사용하는 경우라면, 따로 user을 정의하지 않고, request.user을 이용해도 되지만, 정보를 출력하는 코드에서 reservation.user.last_name을  reservation.request.user.last_name으로 변경할 경우 reservationdp request라는 속성을 모델에서 정의하지 않았기 때문에 오류가 발생합니다.


2.  tests.py reservations에 이용되는 decorator를 위한 테스트코드를 추가해주었습니다.

2022-08-09 06:50 UTC, bigfanoftim approved these changes
LGTM 👍

2022-08-09 06:50 UTC, merged