카카오 소셜 회원가입/로그인
wecode-bootcamp-korea/35-2nd-WnB-backend pull request #8
Opened 2022-08-05 08:12 UTC by ooooo5h

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-08-08 02:49 UTC, bigfanoftim requested changes

2022-08-08 02:49 UTC, bigfanoftim commented on core/utils.py
> +            request.user = user
```suggestion
            request.user         = User.objects.get(id = payload['id'])
```

2022-08-08 02:49 UTC, bigfanoftim commented on core/utils.py
> +        raise ValidationError("PHONE_NUMBER_ERROR")
이 코드는 지금 쓰이지 않는 것 같은데 왜 추가가 되어 있나요?

만약 나중에 어떤 API에 필요한 기능이라면 해당 PR에 올려주세요.

2022-08-08 02:49 UTC, bigfanoftim commented on users/views.py
> +
`get_or_create()`에 `defaults` 옵션을 이용해보세요!

2022-08-08 02:49 UTC, bigfanoftim commented on users/views.py
> +            return JsonResponse({'message':'SIGNIN_SUCCESS', 'token':token}, status=200)
`else`가 필요없어 보입니다!

```python
if not created:
   ...

token = ..

return JsonResponse(..., token)
```

2022-08-08 03:33 UTC, ooooo5h commented on core/utils.py
> +            request.user = user
앗 넵 수정하겠습니다!

2022-08-08 04:41 UTC, ooooo5h commented on users/views.py
> +
defaults 옵션을 사용하면 객체를 생성할 때 사용할 수 있네요 감사합니다!

2022-08-08 04:42 UTC, ooooo5h commented on users/views.py
> +            return JsonResponse({'message':'SIGNIN_SUCCESS', 'token':token}, status=200)
아하 defaults 옵션을 줘서 원하는 데이터로 객체를 생성까지 했으니 if-else문이 필요가 없습니다.  하나로 줄이겠습니다 감사합니다!

2022-08-08 04:47 UTC, ooooo5h commented on core/utils.py
> +        raise ValidationError("PHONE_NUMBER_ERROR")
앗 호준님 생각해보니까 유효성검사는 이미 merge가 된 추가정보 입력 API에 사용되는 기능입니다. 이럴 경우 validation 브랜치를 새로 파서 pr를 작성하면 될까요..?

2022-08-08 09:17 UTC, bigfanoftim requested changes

2022-08-08 09:17 UTC, bigfanoftim commented on users/views.py
> +        return JsonResponse({'message':'SIGNUP_SUCCESS'}, status=201)
기존에 없던 유저가 카카오로 로그인을 시도하더라도 토큰을 줘야겟죠?
```suggestion
        if not created:
            user.kakao_proifile_img = kakao_profile_img
            user.save()
            
        token = jwt.encode({'id':user.id}, settings.SECRET_KEY, settings.ALGORITHM)
    
        return JsonResponse({'message':'SUCCESS', 'token' : token}, status=201 if created else 200)
```

2022-08-08 15:23 UTC, ooooo5h commented on users/views.py
> +        return JsonResponse({'message':'SIGNUP_SUCCESS'}, status=201)
저희 DB에 없는 유저가 카카오로 첫 로그인을 시도한다면 회원가입이 됩니다. 
회원가입이 되면, 사용자 정보를 추가로 입력받아야하고 
해당 기능은 로그인 데코레이터를 사용해 토큰으로 유저의 신원을 확인하고 있습니다.

그렇기 때문에 회원가입시에도 토큰 발급이 필요한거구나 라고 생각하고 코드를 수정했습니다!

저는 로그인할때만 토큰을 발급하는 걸로 알고있었는데, 
회원가입시에도 토큰을 주는 이유가 저게 맞는지 궁금합니다!

2022-08-09 03:41 UTC, bigfanoftim approved these changes
LGTM 👍

2022-08-09 03:41 UTC, merged